services:
  rabbitmq:
    image: 'rabbitmq:3.13.4-management'
    container_name: 'ping-pong-rabbit'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
